image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
    - build
before_script:
    - apt-get update
    - apt-get install zip unzip
    - curl --location --output /usr/local/bin/release-cli "https://release-cli-downloads.s3.amazonaws.com/latest/release-cli-linux-amd64"
build:
    stage: build
    script:
        - dotnet restore
        - wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        - mkdir dalamud
        - unzip latest.zip -d dalamud
        - dotnet build -c Release
    release:
        name: 'Release $CI_COMMIT_TAG'
        tag_name: $CI_COMMIT_TAG
        description: 'Release $CI_COMMIT_TAG'
