image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
    - build
    - release

build:
    stage: build
    rules:
        - if: $CI_COMMIT_TAG
    before_script:
        - apt-get update
        - apt-get install zip unzip
    script:
        - dotnet restore
        - wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        - mkdir dalamud
        - unzip latest.zip -d dalamud
        - dotnet build -c Release
    artifacts:
        expire_in: never
        paths:
            - NextUIPlugin/bin/x64/Release/NextUIPlugin/latest.zip
            - NextUIPlugin/bin/x64/Release/NextUIPlugin/NextUIPlugin.json

release:
    stage: release
    rules:
        - if: $CI_COMMIT_TAG
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    script:
        - |
            release-cli create --name "Release $CI_COMMIT_TAG" --tag-name $CI_COMMIT_TAG \
              --assets-link "{\"name\":\"Release\",\"url\":\"https://gitlab.com/kaminariss/nextui-plugin/-/jobs/artifacts/$CI_COMMIT_TAG/raw/NextUIPlugin/bin/x64/Release/NextUIPlugin/latest.zip?job=build\"}"
