image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
    - build
before_script:
    - apt-get update
    - apt-get install zip unzip
build:
    stage: build
    script:
        - dotnet restore
        - wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        - mkdir dalamud
        - unzip latest.zip -d dalamud
        - dotnet build -c Release