image: mcr.microsoft.com/dotnet/sdk:6.0
stages:
    - build
    - publish

build:
    stage: build
    rules:
        - if: $CI_COMMIT_TAG
    before_script:
        - apt-get update
        - apt-get install zip unzip
    script:
        - dotnet restore
        - wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        - mkdir dalamud
        - unzip latest.zip -d dalamud
        - dotnet build -c Release
    artifacts:
        expire_in: never
        paths:
            - NextUIPlugin/bin/Release/NextUIPlugin/latest.zip
            - NextUIPlugin/bin/Release/NextUIPlugin/NextUIPlugin.json
            - NextUIBrowser/bin/latest.zip

publish:
    stage: publish
    rules:
        -   if: $CI_COMMIT_TAG
    image: node:14.18.0-buster
    before_script:
        - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
        - mkdir -p ~/.ssh
        - chmod 644 ~/.ssh
        - touch ~/.ssh/known_hosts
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - git config --global user.email "runner@gitlab.com"
        - git config --global user.name "Gitlab Runner"
    script:
        - git clone git@gitlab.com:kaminariss/nextui-repo.git nextuirepo
        - cd nextuirepo
        - git fetch --all
        - git checkout main
        - git pull
        - git status
        - node build.js NextUIPlugin https://gitlab.com/kaminariss/nextui-plugin $CI_COMMIT_TAG
        - git add .
        - git status
        - git commit -m "Update $CI_COMMIT_TAG"
        - git status
        - git push