image: mcr.microsoft.com/dotnet/sdk:5.0
stages:
    - install
    - build
install:
    stage: install
    script:
        - dotnet restore
        - sudo apt-get install unzip
        - wget https://goatcorp.github.io/dalamud-distrib/stg/latest.zip
        - mkdir $PWD/dalamud
        - unzip latest.zip -d $PWD/dalamud
        - echo $PWD
build:
    stage: build
    script:
        - dotnet build -c Release