language: csharp
mono: none
dist: xenial
dotnet: 5.0
install:
    - dotnet restore
script:
    - wget https://goatcorp.github.io/dalamud-distrib/latest.zip
    - mkdir $PWD/dalamud
    - unzip latest.zip $PWD/dalamud
    - dotnet build