language: csharp
mono: none
dist: xenial
dotnet: 5.0
install:
    - dotnet restore
script:
    - wget https://goatcorp.github.io/dalamud-distrib/latest.zip -P $TRAVIS_REPO_SLUG
    - unzip $TRAVIS_REPO_SLUG/latest.zip $TRAVIS_REPO_SLUG/dalamud
    - dotnet build